stages:
    - dev
    - production
Deploy to Dev:
  stage: dev
  tags:
    - node
  script:
    - bash ./.gitlab-deploy.dev.sh
  only:
    refs:
      - dev

Deploy to Production:
  stage: production
  tags:
    - node-2
  script:
    - bash ./.gitlab-deploy.prod.sh
  only:
    refs:
      - master

Deploy Master to Dev:
  stage: dev
  tags:
    - node
  script:
    - bash ./.gitlab-deploy.dev-master.sh
  only:
    refs:
      - master