stages:
    - dev
    - production
Deploy to Dev:
  stage: dev
  tags:
    - node
  script:
    - bash ./.gitlab-deploy.dev.sh
  only:
    - dev
    
Deploy to Production:
  stage: production
  tags:
    - node
  script:
    - bash ./.gitlab-deploy.prod.sh
  only:
    - dev
    - master