stages:
  - demo
  - production

demo:
  stage: demo
  tags:
    - node
  script:
    - |
      sudo -i -u $DEMO_USER bash <<-EOF
      cd $DEMO_PATH
      git checkout $CI_COMMIT_REF_NAME
      git pull
      git submodule update --init --recursive
      composer install
      php artisan migrate
      supervisorctl restart $DEMO_SUPERVISOR
      npm install
      npm run production
      sed -i "s/^APP_VERSION=.*$/APP_VERSION=$CI_COMMIT_SHORT_SHA/g" .env
      EOF
  only:
    refs:
      - dev
      - master

production:
  stage: production
  tags:
    - gtp
  script:
    - |
      sudo -i -u $PROD_USER bash <<-EOF
      cd $PROD_PATH
      git checkout $CI_COMMIT_REF_NAME
      git pull
      git submodule update --init --recursive
      composer install
      php artisan migrate
      supervisorctl restart $PROD_SUPERVISOR
      npm install
      npm run production
      sed -i "s/^APP_VERSION=.*$/APP_VERSION=$CI_COMMIT_SHORT_SHA/g" .env
      EOF
  only:
    refs:
      - master
