version: '2'
services:
  storage:
    image: crmplease/laravel-storage
    volumes:
      - ./:/data
    privileged: true

  database:
    image: mysql:5.7
    command: mysqld --sql_mode="" --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=forge
      - MYSQL_USER=forge
      - MYSQL_PASSWORD=forge
    volumes_from:
      - storage
    ports:
      - 3306:3306
    privileged: true

  php-fpm:
    image: crmplease/laravel-php-fpm
    volumes_from:
      - storage
    links:
      - database:database
    ports:
      - 9000:9000
    privileged: true

  nginx:
    image: crmplease/laravel-nginx
    volumes_from:
      - storage
    links:
      - php-fpm:php-fpm
    depends_on:
      - database
      - php-fpm
    ports:
      - 80:80
    privileged: true

  artisan:
    image: crmplease/laravel-artisan
    volumes_from:
      - storage
    depends_on:
      - database
      - php-fpm
      - nginx
    links:
      - database:database
    privileged: true

  composer:
    image: crmplease/laravel-composer
    volumes_from:
      - storage
    depends_on:
      - database
      - php-fpm
      - nginx
    privileged: true

  queue:
    image: crmplease/laravel-queue
    volumes_from:
      - storage
    depends_on:
      - database
      - php-fpm
      - nginx
    links:
      - database:database
    privileged: true

  cron:
    image: crmplease/laravel-cron
    volumes_from:
      - storage
    depends_on:
      - database
      - php-fpm
      - nginx
    links:
      - database:database
    privileged: true

  npm:
    image: crmplease/laravel-npm
    volumes_from:
      - storage
    privileged: true
