<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */
$factory->define(App\CustomerInvoice::class, function (Faker\Generator $faker) {
    return [
		'maventa_id' => null,
		'maventa_tiff' => null,
		'maventa_initiated' => $faker->boolean,
		'currency' => null,
		'data' => null,
		'date' => null,
		'date_due' => null,
		'delivery_date' => null,
		'delivery_type' => null,
		'error_message' => null,
		'invoice_delivery_address' => null,
		'invoice_nr' => null,
		'invoice_seller_information' => null,
		'lang' => null,
		'notes' => null,
		'order_nr' => null,
		'payment_terms' => null,
		'reference_nr' => null,
		'state' => null,
		'status' => null,
		'sum' => null,
		'sum_tax' => null,
		'work_order_nr' => null,
		'company_interest' => null,
		'company_paper_fee' => null,
		'company_reminder' => null,
		'company_comment' => null,
		'company_reference' => null,
		'customer_nr' => Номер клиента,
		'customer_email' => Эл.почта клиента,
		'customer_name' => Название клиента,
		'customer_country' => Страна клиента,
		'customer_state' => Штат, округ, облась клиента,
		'customer_post_code' => Почтовый индекс клиента,
		'customer_post_office' => Почтовый адрес клиента,
		'customer_address1' => Адрес клиента,
		'customer_address2' => Адрес клиента (доп.),
		'customer_contact_p' => Контактное лицо,
		'customer_bid' => BID,
		'customer_ovt' => OVT,
    ];
});
