<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */
$factory->define(App\CustomerInvoice::class, function (Faker\Generator $faker) {
    return [
		'maventa_id' => null,
		'maventa_tiff' => null,
		'maventa_initiated' => $faker->boolean,
		'currency' => null,
		'data' => null,
		'date' => null,
		'date_due' => null,
		'delivery_date' => null,
		'delivery_type' => null,
		'error_message' => null,
		'invoice_delivery_address' => null,
		'invoice_nr' => null,
		'invoice_seller_information' => null,
		'lang' => null,
		'notes' => null,
		'order_nr' => null,
		'payment_terms' => null,
		'reference_nr' => null,
		'state' => null,
		'status' => null,
		'sum' => null,
		'sum_tax' => null,
		'work_order_nr' => null,
		'company_interest' => null,
		'company_paper_fee' => null,
		'company_reminder' => null,
		'company_comment' => null,
		'company_reference' => null,
		'customer_nr' => null,
		'customer_email' => null,
		'customer_name' => null,
		'customer_country' => null,
		'customer_state' => null,
		'customer_post_code' => null,
		'customer_post_office' => null,
		'customer_address1' => null,
		'customer_address2' => null,
		'customer_contact_p' => null,
		'customer_bid' => null,
		'customer_ovt' => null,
		'maventa_paid' => $faker->boolean,
		'maventa_sent_at' => null,
		'customer_reference' => null,
    ];
});
