<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */
$factory->define(App\CustomerRevision::class, function (Faker\Generator $faker) {
    return [
		'revision_type' => null,
		'name' => $faker->unique()->name,
		'legal_name' => null,
		'billing_postcode' => null,
		'billing_address' => null,
		'shipping_postcode' => null,
		'shipping_address' => null,
		'bid' => null,
		'iban' => null,
		'swift' => null,
		'email' => $faker->unique()->safeEmail,
		'phone' => $faker->unique()->phoneNumber,
		'order_interval' => null,
		'comment' => null,
		'calendar_comment' => null,
		'incomterms' => null,
		'terms_of_cooperation' => null,
		'terms_of_delivery' => null,
		'terms_of_equipment' => null,
		'delivery_payer' => null,
		'payment_conditions' => null,
		'pays_vat' => $faker->boolean,
		'archived' => $faker->boolean,
		'nr' => null,
		'country' => null,
		'state' => null,
		'post_code' => null,
		'post_office' => null,
		'address1' => null,
		'address2' => null,
		'contact_p' => null,
		'ovt' => null,
		'y_tunnus' => null,
    ];
});
