# Generated by DBDiff
# On 02/03/2020 10:16:59 am

#---------- UP ----------
ALTER TABLE `customer_revisions` CHANGE `delivery_payer` `delivery_payer` varchar(191) COLLATE utf8_unicode_ci DEFAULT '';
ALTER TABLE `customer_revisions` CHANGE `payment_conditions` `payment_conditions` varchar(191) COLLATE utf8_unicode_ci DEFAULT '';
ALTER TABLE `customer_order_items` CHANGE `products_quantity` `products_quantity` int(10) DEFAULT NULL;
ALTER TABLE `customer_order_items` CHANGE `packages_quantity` `packages_quantity` int(10) DEFAULT NULL;
ALTER TABLE `customer_revisions` CHANGE `shipping_address` `shipping_address` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `customer_revisions` CHANGE `email` `email` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `customers` CHANGE `email` `email` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL;

ALTER TABLE `stock_movements` DROP FOREIGN KEY `stock_movements_supplier_order_id_foreign`;
ALTER TABLE `stock_movements` DROP FOREIGN KEY `stock_movements_stock_id_foreign`;
ALTER TABLE `stock_movements` DROP INDEX `stock_movements_stock_id_foreign`;
ALTER TABLE `stock_movements` DROP INDEX `stock_movements_supplier_order_id_foreign`;
ALTER TABLE `stock_movements` DROP `supplier_order_id`;

ALTER TABLE `customer_revisions` ADD `state` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `customers` ADD `ovt` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `customers` ADD `country` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `customers` ADD `post_code` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `customers` ADD `post_office` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `customers` ADD `address1` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `customers` ADD `address2` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `customers` ADD `contact_p` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `customers` ADD `y_tunnus` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `customers` ADD `archived` tinyint(1) DEFAULT NULL;
ALTER TABLE `product_groups` ADD `product_type_id` bigint(20) unsigned DEFAULT NULL;
ALTER TABLE `product_groups` ADD `image` text COLLATE utf8_unicode_ci;
ALTER TABLE `products` ADD `unit_type` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `users` ADD `email_verified_at` timestamp NULL DEFAULT NULL;
ALTER TABLE `administrators` ADD `locale` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `administrators` ADD `email_verified_at` timestamp NULL DEFAULT NULL;
ALTER TABLE `customers` ADD `nr` int(11) DEFAULT NULL;
ALTER TABLE `customers` ADD `state` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `customers` ADD `price_group_id` bigint(20) unsigned DEFAULT NULL;
ALTER TABLE `customer_revisions` ADD `post_office` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `customer_revisions` ADD `price_group_id` bigint(20) unsigned DEFAULT NULL;
ALTER TABLE `customer_revisions` ADD `archived` tinyint(1) DEFAULT NULL;
ALTER TABLE `customer_revisions` ADD `country` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `customer_order_items` ADD `customer_invoice_id` bigint(20) unsigned DEFAULT NULL;
ALTER TABLE `customer_revisions` ADD `post_code` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `customer_revisions` ADD `nr` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `customer_revisions` ADD `address1` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `customer_revisions` ADD `y_tunnus` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `customer_revisions` ADD `contact_p` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `customer_revisions` ADD `ovt` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL;
ALTER TABLE `customer_revisions` ADD `address2` varchar(191) COLLATE utf8_unicode_ci DEFAULT NULL;
#---------- DOWN ----------
