# Generated by DBDiff
# On 02/03/2020 10:16:59 am

#---------- UP ----------
DROP TABLE IF EXISTS `supplier_order_items`;
DROP TABLE IF EXISTS `supplier_orders`;
DROP TABLE IF EXISTS `suppliers`;
DROP TABLE IF EXISTS `cars`;
DROP TABLE IF EXISTS `transport_sheets`;
#---------- DOWN ----------
