<?php return [
	App\Repositories\Contracts\RegionRepository::class => App\Repositories\Eloquent\RegionRepositoryEloquent::class,
	App\Repositories\Contracts\CompanyRepository::class => App\Repositories\Eloquent\CompanyRepositoryEloquent::class,
	App\Repositories\Contracts\RoleRepository::class => App\Repositories\Eloquent\RoleRepositoryEloquent::class,
	App\Repositories\Contracts\UserRepository::class => App\Repositories\Eloquent\UserRepositoryEloquent::class,
	App\Repositories\Contracts\AdministratorRepository::class => App\Repositories\Eloquent\AdministratorRepositoryEloquent::class,
	App\Repositories\Contracts\BrandRepository::class => App\Repositories\Eloquent\BrandRepositoryEloquent::class,
	App\Repositories\Contracts\PackageTypeRepository::class => App\Repositories\Eloquent\PackageTypeRepositoryEloquent::class,
	App\Repositories\Contracts\ProductGroupRepository::class => App\Repositories\Eloquent\ProductGroupRepositoryEloquent::class,
	App\Repositories\Contracts\ProductRepository::class => App\Repositories\Eloquent\ProductRepositoryEloquent::class,
	App\Repositories\Contracts\StockRepository::class => App\Repositories\Eloquent\StockRepositoryEloquent::class,
	App\Repositories\Contracts\PaymentTypeRepository::class => App\Repositories\Eloquent\PaymentTypeRepositoryEloquent::class,
	App\Repositories\Contracts\CustomerTypeRepository::class => App\Repositories\Eloquent\CustomerTypeRepositoryEloquent::class,
	App\Repositories\Contracts\CustomerRepository::class => App\Repositories\Eloquent\CustomerRepositoryEloquent::class,
	App\Repositories\Contracts\CustomerRevisionRepository::class => App\Repositories\Eloquent\CustomerRevisionRepositoryEloquent::class,
	App\Repositories\Contracts\CustomerOrderRepository::class => App\Repositories\Eloquent\CustomerOrderRepositoryEloquent::class,
	App\Repositories\Contracts\CustomerShipmentRepository::class => App\Repositories\Eloquent\CustomerShipmentRepositoryEloquent::class,

    App\Repositories\Contracts\JobRepository::class => App\Repositories\Eloquent\JobRepositoryEloquent::class,
    App\Repositories\Contracts\FailedJobRepository::class => App\Repositories\Eloquent\FailedJobRepositoryEloquent::class,
];
