<?php

namespace App\Repositories\Eloquent;

use App\Repositories\Contracts\CustomerInvoiceAttachmentRepository;
use Crmplease\MaterialAdmin\Repositories\RepositoryEloquent as BaseRepositoryEloquent;

class CustomerInvoiceAttachmentRepositoryEloquent extends BaseRepositoryEloquent implements CustomerInvoiceAttachmentRepository {}